# Generated by Django 2.1.3 on 2018-11-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudocode', '0002_airport_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='continent',
            new_name='country',
        ),
    ]
