# Generated by Django 2.1.3 on 2018-11-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudocode', '0003_auto_20181103_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='iso_code',
        ),
    ]
